### ISSUE TITLE
在1.18.2de 服务器上出现乱码

### ISSUE THREAD

**Issue by NatsumiXD** [Zaitonn/Motd#1]

**Comment by NatsumiXD** [comment]
D:\kook\project>motd tcp //////
? ?{"description":{"text":"Republic Of Redstone"},"players":{"max":20,"online":1,"sample":[{"id":"-b48d-276fa52a780c","name":"Dream"}]},"version":{"name":"1.18.2","protocol":758}}

**Comment by Zaitonn** [comment]
还没做裁去数据包的头部qwq 可能晚点会搞
~~其实不只是1.18.2 每个版本都这个样子~~

**Comment by NatsumiXD** [comment]
oh
好的
